
#开发环境
spring:
  application:
    name: Lottery_system
  rabbitmq:
    host: 123.56.166.56
    port: 15672
    username: zqq
    password: zqq
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 5

  web:
    resources:
      static-locations: classpath:/static/,file:/Users/zhaoqianqian/Lottery_Pic_System
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Lottery_system?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zqq13127837702
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 8888
      timeout: 60s
#      默认使用lettuce连接池
      lettuce:
        pool:
#          允许最大连接数
          max-active: 8
#          最大空闲连接数
          max-idle: 8
#          最小空闲连接数
          min-idle: 0
#          连接用完时，新的请求等待时间，超过该时间就抛出异常
          max-wait: 5s
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    map-underscore-to-camel-case: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #配置驼峰自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志
  mapper-locations: classpath:mapper/**Mapper.xml
  type-handlers-package: org.mon.lottery_system.dao.handler #替换路径

logging:
  file:
    name: spring-blog.log

sms:
  access-key-id: LTAI5t9mCxCNix6joJuwpU8n
  access-key-secret: 8jZBQ3qt7Z8MmI90ZKEuUdvMYIVW27
  sign-name: 简易的学习网站


#文件上传相关配置
pic:
  local-path: /Users/zhaoqianqian/Lottery_Pic_System






