server:
  port: 8080
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_user?characterEncoding=utf8&useSSL=false
    username: root
    password: zqq13127837702
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 8888
      timeout: 60s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 8
          max-wait: 5s
  rabbitmq:
    addresses: amqp://zqq:zqq@123.56.166.56:8889/blog
    listener:
      simple:
        acknowledge-mode: manual
  mail:
    host: smtp.qq.com
    port: 465
    username: 1781389019@qq.com
    password: kncrzhmvwxqrehfb  # ⚠️ 这里不能填 QQ 密码，必须使用授权码！
    protocol: smtps
    properties:
      personal: "Chase博客社区"
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: user.log
