spring:
  application:
    name: MQ
#   SQLite 结合这个配置，可以自动创建 .db 文件
  datasource:
    url: jdbc:sqlite:./data/meta.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
