spring:
  application:
    name: Eyes
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Lottery_system?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zqq13127837702
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #配置驼峰自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志
  mapper-locations: classpath:mapper/**Mapper.xml
  type-handlers-package: org.mon.lottery_system.dao.handler #替换路径

pic:
  local-path: /Users/zhaoqianqian/Downloads/Eyes/Pic

logging:
  file:
    name: Eyes.log
