spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?characterEncoding=utf8&useSSL=false
    username: root
    password: ZQQ@yyds.666
    driver-class-name: com.mysql.cj.jdbc.Driver

